import type { Metadata } from 'next';
import { Footer } from '../components/Footer/Footer';
import { Header } from '../components/Header/Header';
import '../globals.css';
import { CartProvider } from './context/CartContext';
import { UserProvider } from './context/UserContext';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={styles.main}>
      <div className={styles.page}>
        <CartProvider>
          <UserProvider>
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </CartProvider>
      </div>
    </main>
  );
}
